# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [11]:
print(np.__version__)

1.26.2


#### 3. Create a null vector of size 10 (★☆☆)

In [12]:
nvector = np.zeros(10)
print(nvector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [13]:
arr = np.zeros((3, 4), dtype=np.float64)

memory_size = arr.nbytes

print(f"Memory size of the array: {memory_size}")

Memory size of the array: 96


How to get the documentation of the numpy add function from the command line?#### 5.  (★☆☆)

In [3]:
##python -c "import numpy; help(numpy.add)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [24]:
null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [25]:
import numpy as np
vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [27]:
vector = [1, 2, 3, 4, 5]

# За допомогою slicing (зрізу)
reversed_vector = vector[::-1]

print("Original vector:", vector)
print("Reversed vector:", reversed_vector)


Original vector: [1, 2, 3, 4, 5]
Reversed vector: [5, 4, 3, 2, 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [28]:

matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [29]:
arr = np.array([1, 2, 0, 0, 4, 0])

# Find indices of non-zero elements
indices = np.nonzero(arr)

print(indices)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [30]:
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:")
print(identity_matrix)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [36]:
random_array = np.random.rand(3, 3)
rounded_array = np.round(random_array, 3)
print(rounded_array)

[[0.138 0.857 0.606]
 [0.843 0.287 0.783]
 [0.627 0.295 0.42 ]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [38]:
random_array = np.random.random((10, 10))
random_array = np.round(random_array, 3)
min_value = np.min(random_array)
max_value = np.max(random_array)

print("10x10 Array with Random Values:")
print(random_array)

print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)

10x10 Array with Random Values:
[[0.257 0.979 0.687 0.292 0.894 0.817 0.816 0.134 0.168 0.115]
 [0.728 0.566 0.918 0.833 0.005 0.959 0.532 0.89  0.729 0.447]
 [0.532 0.822 0.891 0.636 0.138 0.893 0.106 0.092 0.03  0.606]
 [0.372 0.365 0.916 0.103 0.679 0.625 0.019 0.221 0.663 0.911]
 [0.93  0.67  0.93  0.456 0.478 0.031 0.686 0.568 0.512 0.873]
 [0.374 0.809 0.337 0.038 0.095 0.951 0.501 0.678 0.089 0.137]
 [0.831 0.496 0.366 0.58  0.449 0.927 0.691 0.091 0.06  0.99 ]
 [0.366 0.32  0.747 0.011 0.797 0.207 0.829 0.79  0.523 0.379]
 [0.507 0.982 0.225 0.261 0.837 0.301 0.978 0.237 0.847 0.704]
 [0.925 0.257 0.678 0.978 0.448 0.645 0.486 0.385 0.432 0.592]]

Minimum Value: 0.005
Maximum Value: 0.99


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [5]:
random_vector = np.random.rand(30)
random_vector = np.round(random_vector, 3)
mean_value = np.mean(random_vector)

print("Random Vector:", random_vector)
print("Mean Value:", mean_value)

Random Vector: [0.319 0.173 0.824 0.42  0.192 0.021 0.048 0.87  0.29  0.704 0.391 0.012
 0.88  0.301 0.334 0.848 0.669 0.132 0.724 0.814 0.833 0.078 0.718 0.609
 0.055 0.676 0.329 0.26  0.25  0.587]
Mean Value: 0.4453666666666667


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [6]:
rows, cols = 5, 5  

array = np.ones((rows, cols), dtype=int)
array[1:-1, 1:-1] = 0
print(array)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
original_array = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

rows, cols = original_array.shape
border_size = 1

new_array = np.zeros((rows + 2 * border_size, cols + 2 * border_size))
new_array[border_size:border_size + rows, border_size:border_size + cols] = original_array
print("Original Array:")
print(original_array)
print("\nArray with Border:")
print(new_array)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:

# 1. nan
# 2. порівняння np.nan з np.nan  True
# 3. np.inf з np.nan  False (оскільки нескінченність не більша за NaN
# 4. np.nan-np.nan=nan
# 5. true (оскільки NaN розглядається як елемент множини)
# 6. порівняння 0.3 з результатом множення 3 на 0.1 False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
matrix = np.diag([1, 2, 3, 4], k=-1)

print(matrix)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
shape = (6, 7, 8)
total_elements = np.prod(shape)
index_100th_element = 99  # Note that indexing is 0-based
index_xyz = np.unravel_index(index_100th_element, shape)
print("Index (x, y, z) of the 100th element:", index_xyz)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
checkerboard = np.tile([[0, 1], [1, 0]], (4, 4))
print(checkerboard)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
random_matrix = np.random.rand(5, 5)
normalized_matrix = (random_matrix - np.min(random_matrix)) / (np.max(random_matrix) - np.min(random_matrix))
print("Original Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
rgba_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])
color_array = np.array([(255, 0, 0, 255), (0, 255, 0, 128)], dtype=rgba_dtype)
print(color_array)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
matrix_A = np.random.random((5, 3))
matrix_B = np.random.random((3, 2))
matrix_C = np.dot(matrix_A, matrix_B)
print("Matrix A (5x3):")
print(matrix_A)
print("\nMatrix B (3x2):")
print(matrix_B)
print("\nResultant Matrix C (5x2):")
print(matrix_C)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [7]:
array_1d = np.array([1, 5, 3, 7, 9, 2, 6, 4, 8, 10])
array_1d[(array_1d >= 3) & (array_1d <= 8)] *= -1
print(array_1d)

[ 1 -5 -3 -7  9  2 -6 -4 -8 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
#9
#10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
#Z**Z: Квадрат
#2 << Z >> 2: Зсуває вліво число 2 на елементи вектора Z, а потім зсуває результат вправо на 2
#Z <- Z: Порівнює кожен елемент вектора Z з його від'ємним значенням (-Z)
#1j*Z: Помножує кожен елемент вектора Z на уявну одиницю 1j
#Z/1/1: Ділить кожен елемент вектора Z на 1 двічі
#Z<Z>Z: Це неправильний вираз. пробуємо порівняти ланцюгати оператори, але такий ланцюг недоступний

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [9]:
# Create a float array
float_array = np.array([2.3, -4.8, 1.5, -3.2, 5.9])

# Round away from zero
rounded_array = np.fix(float_array + 0.5 * np.sign(float_array))

print("Original Float Array:")
print(float_array)

print("\nRounded Array (away from zero):")
print(rounded_array)

Original Float Array:
[ 2.3 -4.8  1.5 -3.2  5.9]

Rounded Array (away from zero):
[ 2. -5.  2. -3.  6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
common_values = np.intersect1d(array1, array2)
print("Common values:", common_values)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [10]:
np.seterr(all='ignore')
np.seterr(all='warn')

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
## False вираз не відповідає дійсності. У NumPy np.sqrt(-1) повертає комплексне число, представлене як NumPy float64 із комплексною частиною, 
##тоді як np.emath.sqrt(-1) повертає комплексне число як комплекс NumPy128.

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [11]:
from datetime import datetime, timedelta
today = datetime.now().date()

yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2023-12-08
Today: 2023-12-09
Tomorrow: 2023-12-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [12]:
from datetime import datetime, timedelta
start_date = datetime(2016, 7, 1)
days_in_july = 31  

date_list = [start_date + timedelta(days=i) for i in range(days_in_july)]
for date in date_list:
    print(date)

2016-07-01 00:00:00
2016-07-02 00:00:00
2016-07-03 00:00:00
2016-07-04 00:00:00
2016-07-05 00:00:00
2016-07-06 00:00:00
2016-07-07 00:00:00
2016-07-08 00:00:00
2016-07-09 00:00:00
2016-07-10 00:00:00
2016-07-11 00:00:00
2016-07-12 00:00:00
2016-07-13 00:00:00
2016-07-14 00:00:00
2016-07-15 00:00:00
2016-07-16 00:00:00
2016-07-17 00:00:00
2016-07-18 00:00:00
2016-07-19 00:00:00
2016-07-20 00:00:00
2016-07-21 00:00:00
2016-07-22 00:00:00
2016-07-23 00:00:00
2016-07-24 00:00:00
2016-07-25 00:00:00
2016-07-26 00:00:00
2016-07-27 00:00:00
2016-07-28 00:00:00
2016-07-29 00:00:00
2016-07-30 00:00:00
2016-07-31 00:00:00


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [19]:
A = np.array([1, 2, 3], dtype=float)
B = np.array([4, 5, 6], dtype=float)
A += B          # A = A + B
A *= -0.5 * A   # A = A * (-A/2)
print(A)

[-12.5 -24.5 -40.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [15]:
random_array = np.random.uniform(0, 10, 5)  # Adjust the size (5 in this example) and range as needed
# Method 1: Using numpy.floor
integer_part_floor = np.floor(random_array)

# Method 2: Using numpy.ceil
integer_part_ceil = np.ceil(random_array)

# Method 3: Using numpy.trunc
integer_part_trunc = np.trunc(random_array)

# Method 4: Using astype(int)
integer_part_astype = random_array.astype(int)

# Print the results
print("Original Array:", random_array)
print("Using floor:", integer_part_floor)
print("Using ceil:", integer_part_ceil)
print("Using trunc:", integer_part_trunc)
print("Using astype(int):", integer_part_astype)

Original Array: [9.85022612 4.10870022 9.71843714 7.69813425 1.12809673]
Using floor: [9. 4. 9. 7. 1.]
Using ceil: [10.  5. 10.  8.  2.]
Using trunc: [9. 4. 9. 7. 1.]
Using astype(int): [9 4 9 7 1]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [16]:
matrix = np.arange(5).reshape((5, 1)) + np.arange(5)
print(matrix)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [17]:

def generate_integers():
    for i in range(10):
        yield i

generated_array = np.fromiter(generate_integers(), dtype=int)
print("Generated Array:", generated_array)

Generated Array: [0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [20]:
vector = np.linspace(0, 1, 12)[1:-1]

print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [22]:
random_vector = np.random.rand(10)
sorted_vector = np.sort(random_vector)

print("Original Random Vector:")
print(random_vector)

print("\nSorted Vector:")
print(sorted_vector)

Original Random Vector:
[0.81231169 0.96248091 0.05818249 0.78193854 0.28785001 0.73520988
 0.01885884 0.92795313 0.4189164  0.78386044]

Sorted Vector:
[0.01885884 0.05818249 0.28785001 0.4189164  0.73520988 0.78193854
 0.78386044 0.81231169 0.92795313 0.96248091]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [23]:
small_array = np.array([1, 2, 3, 4, 5])
sum_np = np.sum(small_array)
sum_builtin = sum(small_array)

print("Sum using np.sum:", sum_np)
print("Sum using Python built-in sum:", sum_builtin)

Sum using np.sum: 15
Sum using Python built-in sum: 15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [24]:
A = np.random.random((3, 3))
B = np.random.random((3, 3))
# Check if arrays A and B are equal
are_equal = np.array_equal(A, B)

print("Array A:")
print(A)

print("\nArray B:")
print(B)

print("\nAre arrays A and B equal?", are_equal)

Array A:
[[0.56107128 0.81259718 0.64021823]
 [0.19830469 0.98234811 0.7466429 ]
 [0.38194259 0.97904334 0.68283739]]

Array B:
[[0.15027423 0.34647975 0.45508345]
 [0.48503643 0.20333628 0.11658714]
 [0.49772343 0.65419029 0.05857949]]

Are arrays A and B equal? False


#### 43. Make an array immutable (read-only) (★★☆)

In [25]:
# Create a sample array
my_array = np.array([1, 2, 3, 4, 5])
my_array.flags.writeable = False

# Try to modify the array (this will raise an error)
# Uncomment the line below to see the error
# my_array[0] = 10

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [26]:
cartesian_coordinates = np.random.random((10, 2))

x = cartesian_coordinates[:, 0]
y = cartesian_coordinates[:, 1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

polar_coordinates = np.column_stack((r, theta))

print("Cartesian Coordinates:")
print(cartesian_coordinates)

print("\nPolar Coordinates:")
print(polar_coordinates)

Cartesian Coordinates:
[[0.26302213 0.7079602 ]
 [0.85205223 0.92842635]
 [0.11331187 0.79124358]
 [0.43363936 0.72293178]
 [0.71343934 0.97887395]
 [0.79488449 0.10842982]
 [0.59007769 0.36196097]
 [0.33292633 0.5743606 ]
 [0.46873973 0.30788184]
 [0.40033627 0.60448669]]

Polar Coordinates:
[[0.75524055 1.21507916]
 [1.26014622 0.82826716]
 [0.79931594 1.42855612]
 [0.84301451 1.03049859]
 [1.21127614 0.94097782]
 [0.80224584 0.13557277]
 [0.6922481  0.55022323]
 [0.66387502 1.04547681]
 [0.56081027 0.58116094]
 [0.7250333  0.98584045]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [27]:
random_vector = np.random.rand(10)
max_index = np.argmax(random_vector)
random_vector[max_index] = 0

print("Original Random Vector:")
print(random_vector)


Original Random Vector:
[0.44429413 0.59789633 0.69689671 0.         0.04658657 0.40809397
 0.47846174 0.2497392  0.93189612 0.72569912]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)